################################### Default Configuration ############################
baseurl = "https://mviewer.netlify.com/"
languageCode = "fr"
title = "mviewer"
theme = "vex-hugo"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/themefisher-fonts.css"
  [[params.plugins.css]]
  URL = "css/owl.carousel.css"
  [[params.plugins.css]]
  URL = "css/magnific-popup.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery-2.1.1.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "js/jquery.magnific-popup.min.js"


###################################### Navigation ######################################
[menu]

  [[menu.main]]
  name = "A propos"
  URL = "feature"
  weight = 2

  [[menu.main]]
  name = "Ils contribuent et développent"
  URL = "gallery"
  weight = 3


########################### Default parameters ##########################
[params]
logo = ""
home = "Accueil"
# Meta data
description = "This is meta description"
author = "mviewer"
# copyright
copyright = "Copyright 2019 &copy; [themefisher](http://www.Themefisher.com) | All right reserved."

  # Preloader
  [params.preloader]
  enable = true
