################################### Default Configuration ############################
baseurl = "https://mviewer.netlify.com/"
theme = "vex-hugo"
title = "mviewer"
# default content language
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
# disable language
disableLanguages = []

################################# language ################################
[languages]
  [languages.fr]
    contentDir = "content/fr"
	languageName = "FR"
	languageCode = "fr-fr"
      [[languages.fr.menu.main]]
      name = "A PROPOS"
      URL = "feature"
      weight = 1
      [[languages.fr.menu.main]]
      name = "PORTFOLIO"
      URL = "portfolio"
      weight = 2
	  [[languages.fr.menu.main]]
      name = "UTILISATEURS"
      URL = "gallery"
      weight = 3
      [[languages.fr.menu.external]]
      name = "TÉLÉCHARGER"
      URL = "https://github.com/geobretagne/mviewer"
      weight = 4
      [[languages.fr.menu.external]]
      name = "DOCUMENTATION"
      URL = "https://mviewerdoc.readthedocs.io/fr/latest/"
      weight = 5
  [languages.en]
	languageName = "EN"
	languageCode = "en-us"
      [[languages.en.menu.main]]
      name = "ABOUT"
      URL = "feature"
      weight = 1
      [[languages.en.menu.main]]
      name = "PORTFOLIO"
      URL = "portfolio"
      weight = 2
      [[languages.en.menu.main]]
      name = "USERS"
      URL = "gallery"
      weight = 3
      [[languages.en.menu.external]]
      name = "DOWNLOAD"
      URL = "https://github.com/geobretagne/mviewer"
      weight = 4
      [[languages.en.menu.external]]
      name = "DOCUMENTATION"
      URL = "https://mviewerdoc.readthedocs.io/fr/latest/"
      weight = 5

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/themefisher-fonts.css"
  [[params.plugins.css]]
  URL = "css/owl.carousel.css"
  [[params.plugins.css]]
  URL = "css/magnific-popup.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery-2.1.1.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "js/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "js/shuffle.min.js"



########################### Default parameters ##########################
[params]
logo = ""
# Meta data
description = "This is meta description"
author = "mviewer"
# copyright
copyright = "Copyright 2020 | Theme : &copy; [themefisher](https://github.com/themefisher/vex-hugo) | All right reserved."

  # Preloader
  [params.preloader]
  enable = true
